import { Branch, SchoolEvent, Notice, Staff } from '../types';

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'branch-sec-14',
    name: 'Siddhartha International School - Sector 14',
    slug: 'siddhartha-international-school-sector-14-gurugram',
    sector: 'Sector 14',
    address: 'Sector 14, Old Judicial Complex Zone, Gurugram, Haryana 122001, India',
    phone: '8368268149',
    email: 'sector14@siddharthaschools.edu.in',
    board: 'CBSE & HBSE',
    classes: 'Play School to Class 12',
    medium: 'English Medium',
    description: 'Siddhartha International School Sector 14 branch delivers high-standard education integrating CBSE and HBSE frameworks from early childhood through senior secondary. Equipped with smart lecture rooms, computer & science laboratories, sports arena, and holistic child development initiatives.',
    principalName: 'Branch Principal [To be updated via Admin]',
    principalPhone: '8368268149',
    principalQualification: 'M.Sc, M.Ed',
    imageUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?q=80&w=1200&auto=format&fit=crop',
    latitude: 28.4732,
    longitude: 77.0428,
    facilities: ['Smart Classrooms', 'Composite Science Lab', 'Computer Laboratory', 'Library & Reading Room', 'Sports Complex', 'CCTV & Safe Campus', 'School Bus Fleet with GPS'],
    seoTitle: 'Siddhartha International School Sector 14 | CBSE & HBSE School in Gurugram',
    seoDescription: 'Official branch of Siddhartha International Group of Schools at Sector 14, Gurugram. English medium education from Play School to Class 12 under CBSE & HBSE.',
    isActive: true,
    isPlaceholder: true,
  },
  {
    id: 'branch-sec-45',
    name: 'Siddhartha International School - Sector 45',
    slug: 'siddhartha-international-school-sector-45-gurugram',
    sector: 'Sector 45',
    address: 'Sector 45, Near HUDA City Centre corridor, Gurugram, Haryana 122003, India',
    phone: '9355135904',
    email: 'sector45@siddharthaschools.edu.in',
    board: 'CBSE',
    classes: 'Play School to Class 12',
    medium: 'English Medium',
    description: 'Serving families around central Gurugram with contemporary academic infrastructure, learner-centric activity zones, science labs, and comprehensive sports training.',
    principalName: 'Branch Principal [To be updated via Admin]',
    principalPhone: '9355135904',
    principalQualification: 'M.A., B.Ed',
    imageUrl: 'https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?q=80&w=1200&auto=format&fit=crop',
    latitude: 28.4485,
    longitude: 77.0694,
    facilities: ['Digital Classrooms', 'Maths Lab', 'Robotics & STEM Lab', 'Badminton Court', 'Medical Infirmary', 'Dedicated Activity Rooms'],
    seoTitle: 'Siddhartha International School Sector 45 Gurugram | CBSE Admissions',
    seoDescription: 'Admissions open at Siddhartha International School Sector 45, Gurugram. Offering modern CBSE education from Play School to Class 12.',
    isActive: true,
    isPlaceholder: true,
  },
  {
    id: 'branch-sec-56',
    name: 'Siddhartha International School - Sector 56',
    slug: 'siddhartha-international-school-sector-56-gurugram',
    sector: 'Sector 56',
    address: 'Sector 56, Golf Course Road Corridor, Gurugram, Haryana 122011, India',
    phone: '8368268149',
    email: 'sector56@siddharthaschools.edu.in',
    board: 'CBSE & HBSE',
    classes: 'Play School to Class 12',
    medium: 'English Medium',
    description: 'Located in the prime residential hub of Sector 56 Gurugram, offering academic rigor, co-curricular arts, sports programs, and safe GPS-tracked bus transit.',
    principalName: 'Branch Principal [To be updated via Admin]',
    principalPhone: '8368268149',
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=1200&auto=format&fit=crop',
    latitude: 28.4312,
    longitude: 77.1025,
    facilities: ['Smart Classrooms', 'Physics & Chemistry Labs', 'Junior Activity Hall', 'Auditorium', 'Volleyball Court', 'Air Conditioned Library'],
    seoTitle: 'Siddhartha International School Sector 56 Gurugram | CBSE & HBSE School',
    seoDescription: 'Leading school in Sector 56 Gurugram by Siddhartha International Group of Schools. English medium curriculum from Kindergarten to Grade 12.',
    isActive: true,
    isPlaceholder: true,
  },
  {
    id: 'branch-sec-82',
    name: 'Siddhartha International School - Sector 82',
    slug: 'siddhartha-international-school-sector-82-gurugram',
    sector: 'Sector 82',
    address: 'Sector 82, New Gurugram Expressway Zone, Gurugram, Haryana 122004, India',
    phone: '9355135904',
    email: 'sector82@siddharthaschools.edu.in',
    board: 'CBSE & HBSE',
    classes: 'Play School to Class 12',
    medium: 'English Medium',
    description: 'Modern campus in New Gurugram offering child-friendly play school spaces, advanced digital interactive boards, and strong foundational education for junior & senior classes.',
    principalName: 'Branch Principal [To be updated via Admin]',
    principalPhone: '9355135904',
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=1200&auto=format&fit=crop',
    latitude: 28.3846,
    longitude: 76.9698,
    facilities: ['Modern Campus', 'Digital Board Classrooms', 'Cricket Nets', 'Karate & Yoga Studio', 'Safe Drinking RO Water', 'GPS Fleet'],
    seoTitle: 'Siddhartha International School Sector 82 New Gurugram | Play School to 12',
    seoDescription: 'New Gurugram branch of Siddhartha International Group of Schools at Sector 82. Dual board CBSE & HBSE education.',
    isActive: true,
    isPlaceholder: true,
  },
  {
    id: 'branch-sohna-rd',
    name: 'Siddhartha International School - Sohna Road',
    slug: 'siddhartha-international-school-sohna-road-gurugram',
    sector: 'Sohna Road',
    address: 'Sohna Road, Near Subhash Chowk, Gurugram, Haryana 122018, India',
    phone: '8368268149',
    email: 'sohnaroad@siddharthaschools.edu.in',
    board: 'CBSE & HBSE',
    classes: 'Play School to Class 12',
    medium: 'English Medium',
    description: 'Providing comprehensive education on the bustling Sohna Road belt with spacious learning areas, qualified teaching mentors, and dedicated remedial support.',
    principalName: 'Branch Principal [To be updated via Admin]',
    principalPhone: '8368268149',
    imageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1200&auto=format&fit=crop',
    latitude: 28.4191,
    longitude: 77.0422,
    facilities: ['Smart Classrooms', 'Robotics Corner', 'Art & Craft Studio', 'Music Room', 'Table Tennis Arena', 'Fleet Bus Services'],
    seoTitle: 'Siddhartha International School Sohna Road Gurugram',
    seoDescription: 'Siddhartha International School on Sohna Road, Gurugram. Quality English Medium education Play School to Class 12.',
    isActive: true,
    isPlaceholder: true,
  },
  {
    id: 'branch-palam-vihar',
    name: 'Siddhartha International School - Palam Vihar',
    slug: 'siddhartha-international-school-palam-vihar-gurugram',
    sector: 'Palam Vihar',
    address: 'Palam Vihar, Sector 23 / 21 Belt, Gurugram, Haryana 122017, India',
    phone: '9355135904',
    email: 'palamvihar@siddharthaschools.edu.in',
    board: 'CBSE & HBSE',
    classes: 'Play School to Class 12',
    medium: 'English Medium',
    description: 'Fostering academic excellence and strong moral values in North Gurugram. Excellent kindergarten wing and certified high-school faculty.',
    principalName: 'Branch Principal [To be updated via Admin]',
    principalPhone: '9355135904',
    imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?q=80&w=1200&auto=format&fit=crop',
    latitude: 28.5085,
    longitude: 77.0371,
    facilities: ['Kindergarten Activity Area', 'Science Labs', 'Library', 'Indoor Games Arena', 'CCTV 24x7', 'Fire Safety Certified'],
    seoTitle: 'Siddhartha International School Palam Vihar Gurugram',
    seoDescription: 'Palam Vihar campus of Siddhartha International Group of Schools. Top CBSE & HBSE education from Play School to Class 12.',
    isActive: true,
    isPlaceholder: true,
  },
  {
    id: 'branch-sec-102',
    name: 'Siddhartha International School - Sector 102',
    slug: 'siddhartha-international-school-sector-102-dwarka-exp-gurugram',
    sector: 'Sector 102',
    address: 'Sector 102, Dwarka Expressway Corridor, Gurugram, Haryana 122006, India',
    phone: '8368268149',
    email: 'sector102@siddharthaschools.edu.in',
    board: 'CBSE & HBSE',
    classes: 'Play School to Class 12',
    medium: 'English Medium',
    description: 'Serving Dwarka Expressway neighborhoods with expansive infrastructure, smart tech-enabled study halls, and holistic student-led club activities.',
    principalName: 'Branch Principal [To be updated via Admin]',
    principalPhone: '8368268149',
    imageUrl: 'https://images.unsplash.com/photo-1588072432836-e10032774350?q=80&w=1200&auto=format&fit=crop',
    latitude: 28.4891,
    longitude: 76.9744,
    facilities: ['Smart Classrooms', 'Multi-Purpose Sports Court', 'Computer Center', 'Performing Arts', 'Infirmary with Nurse', 'Bus Transport'],
    seoTitle: 'Siddhartha International School Sector 102 Dwarka Expressway Gurugram',
    seoDescription: 'Admissions open at Siddhartha International School Sector 102 along Dwarka Expressway, Gurugram.',
    isActive: true,
    isPlaceholder: true,
  },
  {
    id: 'branch-golf-course-ext',
    name: 'Siddhartha International School - Golf Course Extension',
    slug: 'siddhartha-international-school-golf-course-ext-gurugram',
    sector: 'Golf Course Extension',
    address: 'Sector 65, Golf Course Extension Road, Gurugram, Haryana 122102, India',
    phone: '9355135904',
    email: 'gcext@siddharthaschools.edu.in',
    board: 'CBSE',
    classes: 'Play School to Class 12',
    medium: 'English Medium',
    description: 'State-of-the-art educational facility offering balanced learning that emphasizes critical thinking, scientific curiosity, and athletic participation.',
    principalName: 'Branch Principal [To be updated via Admin]',
    principalPhone: '9355135904',
    imageUrl: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?q=80&w=1200&auto=format&fit=crop',
    latitude: 28.4065,
    longitude: 77.0789,
    facilities: ['Language Lab', 'Composite Science Labs', 'Skating Rink', 'Basketball Court', 'Cafeteria & Meals', 'GPS Tracked Buses'],
    seoTitle: 'Siddhartha International School Golf Course Extension Gurugram',
    seoDescription: 'Excellence in CBSE education on Golf Course Extension Road, Gurugram. Siddhartha International Group of Schools.',
    isActive: true,
    isPlaceholder: true,
  },
  {
    id: 'branch-dlf-phase-1',
    name: 'Siddhartha International School - DLF Phase 1',
    slug: 'siddhartha-international-school-dlf-phase-1-gurugram',
    sector: 'DLF Phase 1',
    address: 'DLF Phase 1, Near Arjun Marg, Gurugram, Haryana 122002, India',
    phone: '8368268149',
    email: 'dlf1@siddharthaschools.edu.in',
    board: 'CBSE & HBSE',
    classes: 'Play School to Class 12',
    medium: 'English Medium',
    description: 'Nurturing academic leadership and intellectual discipline with personalized teacher attention and experiential pedagogical techniques.',
    principalName: 'Branch Principal [To be updated via Admin]',
    principalPhone: '8368268149',
    imageUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?q=80&w=1200&auto=format&fit=crop',
    latitude: 28.4795,
    longitude: 77.0984,
    facilities: ['Smart Classrooms', 'Digital Resource Center', 'Junior Fun Zone', 'Taekwondo Coaching', 'Safe Gated Campus', 'Transport'],
    seoTitle: 'Siddhartha International School DLF Phase 1 Gurugram',
    seoDescription: 'Siddhartha International School DLF Phase 1, Gurugram. Comprehensive CBSE & HBSE school.',
    isActive: true,
    isPlaceholder: true,
  },
  {
    id: 'branch-old-rly-rd',
    name: 'Siddhartha International School - Old Railway Road',
    slug: 'siddhartha-international-school-old-railway-road-gurugram',
    sector: 'Old Railway Road',
    address: 'Old Railway Road, Near Bhim Nagar / Jacobpura, Gurugram, Haryana 122001, India',
    phone: '9355135904',
    email: 'railwayrd@siddharthaschools.edu.in',
    board: 'CBSE & HBSE',
    classes: 'Play School to Class 12',
    medium: 'English Medium',
    description: 'Providing trusted educational grounding to historic Gurugram families with affordable excellence, dedicated coaching for board exams, and cultural enrichment.',
    principalName: 'Branch Principal [To be updated via Admin]',
    principalPhone: '9355135904',
    imageUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=1200&auto=format&fit=crop',
    latitude: 28.4651,
    longitude: 77.0253,
    facilities: ['Smart Lecture Rooms', 'Science Laboratories', 'Computer Lab', 'Yoga & Physical Education', 'Safe Van & Bus Routes'],
    seoTitle: 'Siddhartha International School Old Railway Road Gurugram',
    seoDescription: 'Siddhartha International School Old Railway Road Gurugram. Dual board CBSE & HBSE curriculum.',
    isActive: true,
    isPlaceholder: true,
  },
  {
    id: 'branch-south-city-2',
    name: 'Siddhartha International School - South City 2',
    slug: 'siddhartha-international-school-south-city-2-gurugram',
    sector: 'South City 2',
    address: 'South City 2, Sector 49, Gurugram, Haryana 122018, India',
    phone: '8368268149',
    email: 'southcity2@siddharthaschools.edu.in',
    board: 'CBSE & HBSE',
    classes: 'Play School to Class 12',
    medium: 'English Medium',
    description: 'Contemporary learner-centric environment in South City 2 focusing on foundational numeracy, literacy, science labs, and social emotional development.',
    principalName: 'Branch Principal [To be updated via Admin]',
    principalPhone: '8368268149',
    imageUrl: 'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?q=80&w=1200&auto=format&fit=crop',
    latitude: 28.4182,
    longitude: 77.0543,
    facilities: ['Smart Classrooms', 'Robotics & AI Corner', 'Music & Drama Wing', 'Badminton Court', 'Safe GPS Transportation'],
    seoTitle: 'Siddhartha International School South City 2 Gurugram',
    seoDescription: 'Siddhartha International School in South City 2 Gurugram. Admissions open from Nursery to Class 12.',
    isActive: true,
    isPlaceholder: true,
  },
  {
    id: 'branch-sushant-lok',
    name: 'Siddhartha International School - Sushant Lok',
    slug: 'siddhartha-international-school-sushant-lok-gurugram',
    sector: 'Sushant Lok',
    address: 'Sushant Lok Phase 1, Sector 43, Gurugram, Haryana 122009, India',
    phone: '9355135904',
    email: 'sushantlok@siddharthaschools.edu.in',
    board: 'CBSE & HBSE',
    classes: 'Play School to Class 12',
    medium: 'English Medium',
    description: 'Premier campus in Sushant Lok with state-of-the-art classroom facilities, trained educator mentors, and an enriching extracurricular ecosystem.',
    principalName: 'Branch Principal [To be updated via Admin]',
    principalPhone: '9355135904',
    imageUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=1200&auto=format&fit=crop',
    latitude: 28.4592,
    longitude: 77.0781,
    facilities: ['Interactive Smartboards', 'Composite Science Lab', 'Library', 'Dance & Performing Arts', 'Safe Campus Guarding'],
    seoTitle: 'Siddhartha International School Sushant Lok Gurugram',
    seoDescription: 'Siddhartha International School Sushant Lok Gurugram. Admissions open for CBSE & HBSE from Play School to Class 12.',
    isActive: true,
    isPlaceholder: true,
  }
];

export const INITIAL_NOTICES: Notice[] = [
  {
    id: 'notice-admissions-open',
    title: 'Admissions Open for Academic Session 2027-28',
    description: 'Registrations are now open across all 12 branches in Gurugram for Play School to Class 12 under CBSE and HBSE boards. Limited seats available per section to maintain ideal student-teacher ratios.',
    buttonText: 'Submit Admission Enquiry',
    buttonUrl: '/admissions',
    startDate: '2026-09-01',
    endDate: '2027-04-30',
    branchId: 'all',
    branchName: 'All 12 Branches',
    priority: 'Urgent',
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'notice-annual-sports-meet',
    title: 'Inter-Branch Annual Athletic Championship',
    description: 'Annual track and field championship involving all 12 Gurugram campuses scheduled for next month. Parents are warmly invited to cheer for their young athletes.',
    buttonText: 'View Details',
    buttonUrl: '/events',
    startDate: '2026-09-10',
    endDate: '2026-11-30',
    branchId: 'all',
    branchName: 'All 12 Branches',
    priority: 'High',
    isActive: true
  },
  {
    id: 'notice-special-offer',
    title: 'Early Bird Sibling & Merit Concession Scheme',
    description: 'Special concession on registration fees for siblings and meritorious students enrolled across Siddhartha International Group of Schools.',
    buttonText: 'Enquire with Branch',
    buttonUrl: '/admissions',
    startDate: '2026-09-01',
    endDate: '2027-03-31',
    branchId: 'all',
    branchName: 'All 12 Branches',
    priority: 'Normal',
    isActive: true
  }
];

export const INITIAL_EVENTS: SchoolEvent[] = [
  {
    id: 'event-annual-day',
    title: 'Annual Cultural Festival & Prize Distribution',
    slug: 'annual-cultural-festival-2026',
    description: 'A spectacular evening celebrating student artistic talents, theatrical performances, classical and contemporary dance forms, and academic awards presentation by school leadership.',
    date: '2026-10-24',
    branchId: 'all',
    branchName: 'All Branches (Inter-Branch)',
    coverImageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=1200&auto=format&fit=crop',
    photos: [
      'https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=800&auto=format&fit=crop'
    ],
    isPublished: true,
    category: 'Cultural'
  },
  {
    id: 'event-science-exhibition',
    title: 'Inter-Branch STEM & Innovation Fair',
    slug: 'inter-branch-stem-fair-2026',
    description: 'Students demonstrated working robotics models, eco-sustainable energy projects, AI simulations, and scientific experiments under the mentorship of our faculty.',
    date: '2026-11-14',
    branchId: 'branch-sec-14',
    branchName: 'Sector 14 Campus',
    coverImageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?q=80&w=1200&auto=format&fit=crop',
    photos: [
      'https://images.unsplash.com/photo-1532094349884-543bc11b234d?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?q=80&w=800&auto=format&fit=crop'
    ],
    isPublished: true,
    category: 'Academic'
  },
  {
    id: 'event-sports-day',
    title: 'Annual Sports & Athletic Meet',
    slug: 'annual-sports-meet-2026',
    description: 'Fostering sportsmanship, endurance, and camaraderie through track races, relays, gymnastics routines, and team sports tournaments.',
    date: '2026-12-05',
    branchId: 'all',
    branchName: 'All Branches',
    coverImageUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?q=80&w=1200&auto=format&fit=crop',
    photos: [
      'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1526676037777-05a232554f77?q=80&w=800&auto=format&fit=crop'
    ],
    isPublished: true,
    category: 'Sports'
  }
];

export const INITIAL_STAFF: Staff[] = [
  {
    id: 'staff-director-sandeep-kumar',
    name: 'Sandeep Kumar',
    designation: 'Director, Siddhartha International Group of Schools',
    description: 'Leading the pedagogical vision, institutional governance, and infrastructure development across all 12 Gurugram campuses.',
    shortBio: 'Leading the pedagogical vision, institutional governance, and infrastructure development across all 12 Gurugram campuses.',
    phone: '8368268149',
    email: 'director@siddharthaschools.edu.in',
    department: 'Central Executive Leadership',
    photoUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=800&auto=format&fit=crop',
    staffType: 'central',
    branchId: null,
    branchName: 'All Gurugram Campuses (Central)',
    qualification: 'M.A., M.Ed.',
    experience: '20+ Years',
    displayOrder: 1,
    isActive: true,
    isLeadership: true,
  },
  {
    id: 'staff-manager-kalpna-kumari',
    name: 'Kalpna Kumari',
    designation: 'Manager, Siddhartha International Group of Schools',
    description: 'Overseeing parent engagement, administrative operations, student welfare, and campus coordination across all branches.',
    shortBio: 'Overseeing parent engagement, administrative operations, student welfare, and campus coordination across all branches.',
    phone: '9355135904',
    email: 'manager@siddharthaschools.edu.in',
    department: 'Central Administration & Operations',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=800&auto=format&fit=crop',
    staffType: 'central',
    branchId: null,
    branchName: 'All Gurugram Campuses (Central)',
    qualification: 'M.B.A., B.Ed.',
    experience: '16+ Years',
    displayOrder: 2,
    isActive: true,
    isLeadership: true,
  },
  {
    id: 'staff-sec14-principal',
    name: 'Dr. Meenakshi Sharma',
    designation: 'Principal',
    description: 'Dedicated to fostering an inclusive atmosphere that harmonizes academic excellence with individual student character building.',
    shortBio: 'Dedicated to fostering an inclusive atmosphere that harmonizes academic excellence with individual student character building.',
    photoUrl: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?q=80&w=600&auto=format&fit=crop',
    qualification: 'M.Sc., M.Ed., Ph.D in Education Leadership',
    experience: '18+ Years',
    department: 'Academics & School Administration',
    staffType: 'branch',
    branchId: 'branch-sec-14',
    branchName: 'Siddhartha International School - Sector 14',
    phone: '8368268149',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'staff-sec14-vp',
    name: 'Rajesh Verma',
    designation: 'Academic Coordinator',
    description: 'Spearheading curriculum delivery, modern teacher training workshops, and activity-based learning modules.',
    shortBio: 'Spearheading curriculum delivery, modern teacher training workshops, and activity-based learning modules.',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop',
    qualification: 'M.A. English, B.Ed',
    experience: '12+ Years',
    department: 'Secondary Academics',
    staffType: 'branch',
    branchId: 'branch-sec-14',
    branchName: 'Siddhartha International School - Sector 14',
    phone: '9355135904',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'staff-sec95-principal',
    name: 'Sunita Rao',
    designation: 'Headmistress',
    description: 'Experienced in early foundational pedagogy, experiential numeracy, and child-safe environment administration.',
    shortBio: 'Experienced in early foundational pedagogy, experiential numeracy, and child-safe environment administration.',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=600&auto=format&fit=crop',
    qualification: 'M.Sc., B.Ed.',
    experience: '14+ Years',
    department: 'Primary & Middle Wing',
    staffType: 'branch',
    branchId: 'branch-sec-95',
    branchName: 'Siddhartha International School - Sector 95',
    phone: '8368268149',
    displayOrder: 1,
    isActive: true,
  }
];
